#!/usr/bin/env node
/**
 * Copies only the 48 needed flag SVGs out of flag-icons (devDependency)
 * into src/assets/flags/ and generates src/assets/flags.css.
 * Generated output is committed; re-run only if teams.json changes.
 *
 * Usage: npm run build-flags
 */
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import path from 'node:path'

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)))
const teams = JSON.parse(readFileSync(path.join(root, 'data/teams.json'), 'utf8'))
const srcDir = path.join(root, 'node_modules/flag-icons/flags/4x3')
const outDir = path.join(root, 'src/assets/flags')
mkdirSync(outDir, { recursive: true })

const codes = [...new Set(teams.map((t) => t.iso2))].sort()
let css = `/* Generated by scripts/build-flags.mjs — do not edit by hand. */
.fi {
  display: inline-block;
  background-size: cover;
  background-position: 50%;
  background-repeat: no-repeat;
}
`
for (const code of codes) {
  copyFileSync(path.join(srcDir, `${code}.svg`), path.join(outDir, `${code}.svg`))
  css += `.fi-${code} { background-image: url('./flags/${code}.svg'); }\n`
}
writeFileSync(path.join(root, 'src/assets/flags.css'), css)
console.log(`Wrote ${codes.length} flags.`)
